# Generated by Django 4.2.30 on 2026-04-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('dorm_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price_egp', models.IntegerField()),
                ('distance_km', models.FloatField()),
                ('room_type', models.CharField(max_length=50)),
                ('gender_policy', models.CharField(max_length=50)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_laundry', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('landlord_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='landlord_ids/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('budget_min_egp', models.IntegerField()),
                ('budget_max_egp', models.IntegerField()),
                ('preferred_distance_km', models.FloatField()),
                ('preferred_room_type', models.CharField(max_length=50)),
                ('needs_wifi', models.BooleanField(default=False)),
                ('needs_kitchen', models.BooleanField(default=False)),
                ('needs_laundry', models.BooleanField(default=False)),
                ('needs_ac', models.BooleanField(default=False)),
                ('needs_gym', models.BooleanField(default=False)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='student_ids/')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_rating', models.FloatField()),
                ('landlord_rating', models.FloatField()),
                ('final_rating', models.FloatField()),
                ('dorm_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('landlord_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.dorm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='DormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dorm_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.dorm')),
            ],
        ),
        migrations.AddField(
            model_name='dorm',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dorms', to='api.landlord'),
        ),
    ]
