# Generated by Django 4.2.30 on 2026-04-20 18:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='budget_max_egp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='budget_min_egp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='needs_gym',
        ),
        migrations.RemoveField(
            model_name='student',
            name='preferred_distance_km',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='New Student', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='dorm_id',
            field=models.CharField(default=api.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=api.models.generate_random_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
