# Generated by Django 4.2.30 on 2026-04-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_budget_max_egp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='gender_policy',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='has_gym',
        ),
        migrations.AddField(
            model_name='dorm',
            name='address',
            field=models.CharField(default='No Address', max_length=255),
        ),
    ]
