# Generated by Django 4.2.30 on 2026-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_location_dorm_bathrooms_dorm_bedrooms_dorm_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('banned', 'Banned')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('banned', 'Banned')], default='pending', max_length=20),
        ),
    ]
