# Generated by Django 4.2.30 on 2026-04-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bookingrequest_dorm_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='api.dorm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_dorms', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'dorm')},
            },
        ),
    ]
