# Generated by Django 4.2.30 on 2026-04-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rating_comment_rating_is_anonymous_studentrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
