# Generated by Django 4.2.30 on 2026-04-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dorm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
