# Generated by Django 4.2.30 on 2026-04-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_landlord_gender_student_email_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
