# Generated by Django 4.2.30 on 2026-04-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_siterating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='gender_preference',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10),
        ),
    ]
