# Generated by Django 4.2.30 on 2026-04-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dorm_gender_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dorm',
            name='has_scenic_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dorm',
            name='has_smart_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dorm',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dorm',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_scenic_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_smart_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LandlordRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_landlord_ratings', to='api.landlord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_landlord_ratings', to='api.student')),
            ],
        ),
    ]
