# Generated by Django 4.2.30 on 2026-04-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='is_chat_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='contact_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.contactmessage'),
        ),
    ]
