# Generated by Django 4.2.30 on 2026-04-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_message_is_chat_closed_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='message',
            name='is_chat_closed',
            field=models.BooleanField(default=False, verbose_name='Is Chat Locked'),
        ),
    ]
