# Generated by Django 4.2.30 on 2026-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preferences_set',
            field=models.BooleanField(default=False),
        ),
    ]
