# Generated by Django 4.2.30 on 2026-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='gender_preference',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
