# Generated by Django 4.2.30 on 2026-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_dorm_gender_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='budget_max_egp',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_distance_km',
            field=models.FloatField(default=5.0),
        ),
    ]
