# Generated by Django 4.2.30 on 2026-05-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_student_budget_max_egp_student_preferred_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='gender_policy',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='dorm',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dorm',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dorm',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='budget_min_egp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_gym',
            field=models.BooleanField(default=False),
        ),
    ]
