# -*- coding: utf-8 -*-
"""DORMLINKX2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZTJo5m2d4D3c5NsjRal3zRwcCn19wS2
"""

!pip install pandas
!pip install -U scikit-learn
!pip install numpy==1.26.4
!pip install scikit-surprise

import pandas as pd
import numpy as np
import sklearn as sk
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
from surprise import SVD, Dataset, Reader
from surprise.model_selection import train_test_split as surprise_split
from surprise import accuracy

dorms= pd.read_csv('DORM.csv')
rating= pd.read_csv('RATE.csv')
students= pd.read_csv('STUDENT.csv')
print(dorms)
print(rating)
print(students)

import json

with open("/content/ai_dataset_mapping.json", "r") as f:
    semantic_map = json.load(f)

def normalize(data, mapping):
    return {
        mapping.get(k, k): v
        for k, v in data.items()
    }

def filter_dorms(student):

    filtered = dorms[
        (dorms["price_egp"] <= student["budget_max_egp"]) &
        (dorms["distance_km"] <= student["preferred_distance_km"])&
        (dorms["is_reported"] == False) &
        (dorms["is_available"] == True) &
        (
            (dorms["gender_policy"] == "Mixed") |
            (dorms["gender_policy"] == student["gender"])
        )
    ]

    return filtered

le_room = LabelEncoder()
dorms["room_type_enc"] = le_room.fit_transform(dorms["room_type"])
students["room_type_enc"] = le_room.transform(students["preferred_room_type"])
le_gender = LabelEncoder()
dorms["gender_policy_enc"] = le_gender.fit_transform(dorms["gender_policy"])
students["gender_enc"] = le_gender.transform(students["gender"])

students["needs_wifi"]=students["needs_wifi"].astype(int)
students["needs_kitchen"]=students["needs_kitchen"].astype(int)
students["needs_laundry"]=students["needs_laundry"].astype(int)
students["needs_ac"]=students["needs_ac"].astype(int)
students["needs_gym"]=students["needs_gym"].astype(int)
dorms["has_laundry"]=dorms["has_laundry"].astype(int)
dorms["has_ac"]=dorms["has_ac"].astype(int)
dorms["has_gym"]=dorms["has_gym"].astype(int)
dorms["has_wifi"]    = dorms["has_wifi"].astype(int)
dorms["has_kitchen"] = dorms["has_kitchen"].astype(int)

scaler = StandardScaler()
dorms[["price_scaled", "distance_scaled"]] = scaler.fit_transform(
    dorms[["price_egp", "distance_km"]]
)
student_features_to_scale = students[["budget_max_egp", "preferred_distance_km"]].copy()
student_features_to_scale.columns = ["price_egp", "distance_km"]

students[["budget_scaled", "distance_scaled"]] = scaler.transform(
    student_features_to_scale
)

knn=NearestNeighbors(n_neighbors=5,metric="euclidean")
dorm_features = dorms[[
    "price_scaled",
    "distance_scaled",
    "room_type_enc",
    "has_wifi",
    "has_kitchen",
    "has_laundry",
    "has_ac",
    "gender_policy_enc",
    "has_gym"
]]

def get_seen_dorms(student_id):
    return set(train_ratings[train_ratings["student_id"] == student_id]["dorm_id"])

def get_cbf_recommendations(student_id):

    student = students[students["student_id"] == student_id].iloc[0]
    filtered = filter_dorms(student)

    if len(filtered) == 0:
        return {}

    features = filtered[[
        "price_scaled","distance_scaled","room_type_enc",
        "has_wifi","has_kitchen","has_laundry",
        "has_ac","gender_policy_enc","has_gym"
    ]]

    student_vector = np.array([[
        student["budget_scaled"],
        student["distance_scaled"],
        student["room_type_enc"],
        student["needs_wifi"],
        student["needs_kitchen"],
        student["needs_laundry"],
        student["needs_ac"],
        student["gender_enc"],
        student["needs_gym"]
    ]])

    knn = NearestNeighbors(n_neighbors=len(filtered))
    knn.fit(features)

    distances, indices = knn.kneighbors(student_vector)

    scores = {}
    for i, idx in enumerate(indices[0]):
        dorm_id = filtered.iloc[idx]["dorm_id"]
        scores[dorm_id] = np.exp(-distances[0][i] * 2) # Fixed: Changed 'distance' to 'distances[0][i]'

    return scores

user_item_matrix = rating.pivot_table(
    index='student_id',
    columns='dorm_id',
    values='final_rating'
)

print(user_item_matrix.shape)
print(user_item_matrix.head())

reader = Reader(rating_scale=(1, 5))

data = Dataset.load_from_df(rating[['student_id','dorm_id','final_rating']], reader)

trainset, testset = surprise_split(data, test_size=0.2, random_state=42)

train_ratings_list = []
for uid, iid, r in trainset.all_ratings():
    train_ratings_list.append([trainset.to_raw_uid(uid), trainset.to_raw_iid(iid), r])
train_ratings = pd.DataFrame(train_ratings_list, columns=['student_id', 'dorm_id', 'final_rating'])

print("Training ratings:", trainset.n_ratings)
print("Test ratings:", len(testset))

svd = SVD(n_factors=100, n_epochs=30, lr_all=0.005, reg_all=0.02, random_state=42)
svd.fit(trainset)

predictions = svd.test(testset)
rmse = accuracy.rmse(predictions, verbose=False)
print(f"RMSE: {rmse:.4f}")

test_ratings = pd.DataFrame(testset, columns=["student_id","dorm_id","final_rating"])

def get_cf_recommendations(student_id):

    student = students[students["student_id"] == student_id].iloc[0]
    filtered = filter_dorms(student)

    if len(filtered) == 0:
        return {}

    scores = {}

    for dorm_id in filtered["dorm_id"]:
        pred = svd.predict(str(student_id), str(dorm_id)).est
        scores[dorm_id] = pred

    return dict(sorted(scores.items(), key=lambda x: x[1], reverse=True))

def normalize_scores(scores_dict):

    if not scores_dict:
        return {}

    vals = np.array(list(scores_dict.values()))
    min_v, max_v = vals.min(), vals.max()

    if max_v == min_v:
        return {k: 1 for k in scores_dict}

    return {
        k: (v - min_v) / (max_v - min_v)
        for k, v in scores_dict.items()
    }

def get_dynamic_weights(student_id):

    n = train_ratings[train_ratings["student_id"] == student_id].shape[0]

    if n == 0:
        return 1.0, 0.0   # cold start → CBF

    elif n < 5:
        return 0.7, 0.3

    elif n < 10:
        return 0.5, 0.5

    else:
        return 0.2, 0.8   # heavy CF
def recommend_hybrid(student_id, k=5):

    cbf_scores = get_cbf_recommendations(student_id)
    cf_scores = get_cf_recommendations(student_id)
    seen = get_seen_dorms(student_id)
    all_dorms = (set(cbf_scores.keys()) | set(cf_scores.keys())) - seen
    if not cbf_scores and not cf_scores:
        return "No suitable dorms"

    cbf_scores = normalize_scores(cbf_scores)
    cf_scores = normalize_scores(cf_scores)

    w_cbf, w_cf = get_dynamic_weights(student_id)

    final_scores = {}
    popularity = rating.groupby("dorm_id").size().to_dict()
    for dorm in all_dorms:
        s_cbf = cbf_scores.get(dorm, 0)
        s_cf  = cf_scores.get(dorm, 0)

        pop = popularity.get(dorm, 1)

        final_scores[dorm] = (
    w_cbf * s_cbf +
    w_cf * (s_cf ** 1.1) +
    0.2 * np.log(1 + pop)
)

    # sort
    ranked = sorted(final_scores.items(), key=lambda x: x[1], reverse=True)

    top_ids = [d[0] for d in ranked[:k]]

    return dorms[dorms["dorm_id"].isin(top_ids)]

def precision_at_k(student_id, k=5):
    recommendations = get_cbf_recommendations(student_id)

    if isinstance(recommendations, str):
        return None

    relevant = rating[rating['student_id'] == student_id][['dorm_id', 'relevance_label']]


    recommended_dorm_ids = list(recommendations.keys())


    merged = pd.DataFrame({'dorm_id': recommended_dorm_ids}).merge(relevant, on='dorm_id', how='inner')

    if len(merged) == 0:
        return None

    return merged['relevance_label'].sum() / len(merged)
def mean_precision_at_k(k=5):
    scores = []

    for student_id in students['student_id']:
        score = precision_at_k(student_id, k=k)
        if score is not None:
            scores.append(score)

    if len(scores) == 0:
        return None

    print(f"حُسبت على {len(scores)} طالب من {len(students)}")
    return sum(scores) / len(scores)

print(f"Mean Precision@5: {mean_precision_at_k(5):.4f}")

def precision_at_k_hybrid(student_id, k=5):
    recommendations =recommend_hybrid(student_id, k=k)

    if isinstance(recommendations, str):
        return None

    relevant = rating[rating['student_id'] == student_id][['dorm_id', 'relevance_label']]
    merged = recommendations.merge(relevant, on='dorm_id', how='inner')

    if len(merged) == 0:
        return None

    return merged['relevance_label'].sum() / len(merged)

def mean_precision_at_k_hybrid(k=5):
    scores = []
    for student_id in students['student_id']:
        score = precision_at_k_hybrid(student_id, k=k)
        if score is not None:
            scores.append(score)

    print(f"حُسبت على {len(scores)} طالب من {len(students)}")
    return sum(scores) / len(scores)

print(f"Hybrid Precision@5: {mean_precision_at_k_hybrid(5):.4f}")

def get_top_k_dorm_ids_from_scores(scores_dict, k):
    if not scores_dict:
        return []
    sorted_dorms = sorted(scores_dict.items(), key=lambda item: item[1], reverse=True)
    return [dorm_id for dorm_id, _ in sorted_dorms[:k]]

def precision_at_k(student_id, k=5):

    recommended_scores = get_cbf_recommendations(student_id)


    rec_ids = get_top_k_dorm_ids_from_scores(recommended_scores, k)

    if not rec_ids:
        return 0

    relevant = test_ratings[
        (test_ratings["student_id"] == student_id) &
        (test_ratings["final_rating"] >= 3.5)
    ]["dorm_id"].tolist()

    return len(set(rec_ids) & set(relevant)) / len(rec_ids)

def cf_precision_at_k(student_id, k=5):

    recommended_scores = get_cf_recommendations(student_id)


    rec_ids = get_top_k_dorm_ids_from_scores(recommended_scores, k)

    if not rec_ids:
        return 0

    relevant = test_ratings[
        (test_ratings["student_id"] == student_id) &
        (test_ratings["final_rating"] >= 3.5)
    ]["dorm_id"].tolist()

    return len(set(rec_ids) & set(relevant)) / len(rec_ids)

def hybrid_precision_at_k(student_id, k=5):
    recommended = recommend_hybrid(student_id, k)

    if isinstance(recommended, str) or recommended.empty:
        return 0

    rec_ids = recommended["dorm_id"].tolist()

    relevant = test_ratings[
        (test_ratings["student_id"] == student_id) &
        (test_ratings["final_rating"] >= 3.5)
    ]["dorm_id"].tolist()

    if len(rec_ids) == 0:
        return 0

    return len(set(rec_ids) & set(relevant)) / len(rec_ids)
scores = []

for sid in students["student_id"]:
    score = precision_at_k(sid)
    scores.append(score)

print("Mean Precision@5:", sum(scores) / len(scores))

import random

def random_precision_at_k(student_id, k=5):

    dorm_ids = dorms["dorm_id"].tolist()
    random_recs = random.sample(dorm_ids, k)

    relevant = test_ratings[
        (test_ratings["student_id"] == student_id) &
        (test_ratings["final_rating"] >= 3.5)
    ]["dorm_id"].tolist()

    if len(random_recs) == 0:
        return 0

    return len(set(random_recs) & set(relevant)) / len(random_recs)

cbf_scores = []
cf_scores = []
hybrid_scores = []
rand_scores = []

valid_students = test_ratings["student_id"].unique()

for sid in valid_students:
    cbf_scores.append(precision_at_k(sid))
    cf_scores.append(cf_precision_at_k(sid))
    hybrid_scores.append(hybrid_precision_at_k(sid))
    rand_scores.append(random_precision_at_k(sid))

print("CBF:", sum(cbf_scores)/len(cbf_scores))
print("CF:", sum(cf_scores)/len(cf_scores))
print("Hybrid:", sum(hybrid_scores)/len(hybrid_scores))
print("Random:", sum(rand_scores)/len(rand_scores))